Upgrade Holy Build Box and bump packages
Changes in HBB 2.0.0:

 * OpenSSL has been upgraded to 1.0.2q.
 * libcurl has been upgraded to 7.63.0.
 * ccache has been upraded to 3.5.
 * SQLite has been upgraded to 2018-3260000.
 * pkg_config has been upgraded to 0.29.2.
 * cmake has been upgraded to 3.13.2.
 * Python has been upgraded to 2.7.15.
 * Automake has been upgraded to 1.16.1.
 * M4 has been upgraded to 1.4.18.

Upgraded pacakges for static linking:
curl: 7.62.0 -> 7.63.0
git: 2.19.2 -> 2.20.1
gnupg: 2.2.11 -> 2.2.12
libassuan: 2.5.1 -> 2.5.2
libgpg_error: 1.32 -> 1.33
rubies: 2.4.4 -> 2.4.5, + 2.5.3
rubygems: 2.7.6 -> 3.0.0

Fixup Build:

Fix yum/docker fs bug
Install libiconv because the one in glibc is broken
Tell git and gnupg where to find libiconv
Add new rvm key